language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
